### ISSUE TITLE
error on labelling cells

### ISSUE THREAD

**Issue by andynkili** [abcwcm/Notaras_MolPsy#1]
First, thank you for providing your code.
Second: I was trying to use your code for labelling cells with the Nowakowski dataset.
However when I try to create the sce object I have the following error:
```
nowa.sce <- SingleCellExperiment(assays = list(logcounts = logtpm),
+                                  colData = cold[colnames(logtpm),])
Error in if (!ok) { : missing value where TRUE/FALSE needed
```
Previous line of codes seem to have run fine.
This error happen when a value is compare to NA and when I check the SingleCellExperiment function:
```

SingleCellExperiment
function (..., reducedDims = list(), altExps = list(), rowPairs = list(), 
    colPairs = list(), mainExpName = NULL) 
{
    se <- SummarizedExperiment(...)
    if (!is(se, "RangedSummarizedExperiment")) {
        se <- as(se, "RangedSummarizedExperiment")
    }
    .rse_to_sce(se, reducedDims = reducedDims, altExps = altExps, 
        rowPairs = rowPairs, colPairs = colPairs, mainExpName = mainExpName)
}
<bytecode: 0x000002de7b4dfbd0>
<environment: namespace:SingleCellExperiment>
```
The issue seems to come from **if (!is(se, "RangedSummarizedExperiment"))**, but I don't know how can I fix this.
Have you any idea?

Best,
Andy

**Comment by friedue** [comment]
Let's see if we can figure it out. I'm not surprised that there'll be errors as packages have developed quite rapidly in the past 2 years. Do you have NAs in the `logtpm` object?

**Comment by andynkili** [comment]
I checked and it seems there are no NAs in `logtpm`:
```
any(is.na(logtpm))
[1] FALSE
```

**Comment by friedue** [comment]
and `cold[colnames(logtpm),]`? maybe there's an issue with the subsetting?

**Comment by andynkili** [comment]
Indeed there was Nas in `cold[colnames(logtpm),]`.
The number of cells did not match between `cellInf` and `logtpm` because you removed the ''unknown'' cluster interpretations with `cellinf <- cellinf[ !grepl("^Unknown", Cluster.Interpretation)]`.

I kept them and was able to create the singleCellExperiment object (I just hope I won't have too many "unkown"-labeled cells).
Thank you for your insight on the matter.

Have a great day,
Andy
